### ISSUE TITLE
Фогстрим ревью

### ISSUE THREAD

**Issue by nikvst** [RebekoDev/SiteForFogstream#1]
1. БД
Кажется задание про БД было на нормализацию. Позицию и местоположение нужно было вынести в отдельные таблицы, а вот `window` как раз можно было оставить у сотрудника в `JSONField`

2. Dockerfile
Смущает вот эта строка 
`ADD . /src/`
Если копировать вообще всю репу в контейнер, то неплохо бы описывать файл `.dockerignore`. Или можно просто копировать только то, что будет использоваться в контейнере.

3. gitignore
В репозиторий необходимо положить файл `.gitignore` и указать там все, чего в общем репозитории не должно быть (`__pycache__`, например)

4. settings.py
Настройки лучше выносить из settings.py наружу (в json, yaml, ini файлы или в переменные окружения), а то у тебя secret_key и пароль от почты торчит на весь интернет.

5. Комментарии
Куски закомменченого кода лучше убирать из проекта, они никому не нужны.

6. models.py
Моделям и полям моделей стоит указывать `verbose_name`.
Имена классов должны писаться с большой буквы

7. pep8
Сортировки импортов и их группировки, отступы и прочее - с этим плохо. Попробуй прогнать свой код через flake8/pylint и isort.

8. Тесты
Тестов нет, хотя они были одним из пунктов тестового задания

9. parser.py
`
u = requests.get('http://jsonplaceholder.typicode.com/users')` вот этот код исполнится при импорте parser.py, то есть данные там будут актуальными только в момент старта проекта. Это не хорошо, этот запрос нужно было делать в функции.
При работе с сетью нужно обрабатывать ошибки - как исключения, которые могут падать при проблемах с сетью, так и коды ответа сервера (нам помимо "200" может прийти еще много других кодов и надо проверять, прислал нам сервер то что мы ждали или нет)

10. views.py
https://github.com/RebekoDev/SiteForFogstream/blob/master/testSite/views.py#L52
кажется здесь пропущен `return`

**Comment by RebekoDev** [comment]
Спасибо за фидбэк!
1. Неправильно понял формулировку: "Необходимо оптимизировать базу данных.",
моя ошибка.
7. Как считаете, имеет ли смысл использовать autopep8 и pylint или лучше
самостоятельно форматировать?

чт, 5 сент. 2019 г. в 10:58, Nikita Vstovsky <notifications@github.com>:

**Comment by nikvst** [comment]
1. почитай про нормальные формы
7. Крайне рекомендую использовать линтеры - flake8, pylint.
